import { StyleSheet } from 'react-native';

export const createStyles = (theme: any, fonts: any, isDarkMode: boolean) => StyleSheet.create({
  contentContainer: {
    alignItems: 'center',
    maxWidth: 400,
    width: '100%',
    paddingBottom: 0,
  },
  sosTitle: {
    fontSize: fonts.title + 6,
    fontWeight: 'bold',
    color: isDarkMode ? '#FFFFFF' : theme.primary,
    textAlign: 'center',
    marginTop: 50,
    marginBottom: 30,
  },
  infoButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: theme.primary,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    position: 'absolute',
    top: 50,
    right: 20,
    zIndex: 1000,
  },
  infoButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  sosButtonContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 40,
    position: 'relative',
  },
  sosOuterCircle: {
    position: 'absolute',
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: 'rgba(255, 120, 120, 0.25)',
  },
  sosOuterCircle2: {
    position: 'absolute',
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: 'rgba(255, 150, 150, 0.18)',
  },
  rippleCircle: {
    position: 'absolute',
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: 'rgba(255, 150, 150, 0.25)',
    borderWidth: 2,
    borderColor: 'rgba(255, 160, 160, 0.3)',
  },
  sosButton: {
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: '#FF4444',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#FF4444',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  sosButtonTextContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  sosButtonMainText: {
    color: '#FFFFFF',
    fontSize: fonts.title + 6,
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: 4,
  },
  sosButtonSubText: {
    color: '#FFFFFF',
    fontSize: fonts.subtitle,
    opacity: 0.8,
    textAlign: 'center',
  },
  sosButtonSubText2: {
    color: '#FFFFFF',
    fontSize: fonts.caption - 1,
    opacity: 0.8,
    textAlign: 'center',
    marginTop: 6,
    lineHeight: fonts.caption + 2,
  },
  sosHistoryContainer: {
    marginTop: 20,
    width: '100%',
    maxWidth: 400,
    minHeight: 400,
    flex: 1,
    marginBottom: 10,
    paddingBottom: 0,
  },
  statusMessage: {
    marginTop: 12,
    textAlign: 'center',
    color: isDarkMode ? '#CBD5F5' : theme.secondaryText,
    fontSize: fonts.caption,
  },
});

