import { StyleSheet } from 'react-native';

export const createStyles = (theme: any, fonts: any, isDarkMode: boolean) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
  },
  mainContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingBottom: 0,
  },
  bottomNav: {
    flexDirection: 'row',
    backgroundColor: '#2d3480',
    borderTopWidth: 1,
    borderTopColor: theme.border,
    paddingVertical: 8,
    paddingHorizontal: 2,
    paddingBottom: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 8,
    minHeight: 70,
    alignItems: 'center',
    justifyContent: 'space-around',
    position: 'relative',
  },
  regularTabButton: {
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingVertical: 2,
    paddingHorizontal: 4,
    paddingBottom: 8,
    borderRadius: 12,
    marginHorizontal: 1,
    minWidth: 40,
    flex: 1,
  },
  activeTabButton: {
    backgroundColor: 'rgba(74, 144, 226, 0.3)',
    paddingHorizontal: 0,
    marginHorizontal: -2,
  },
  tabIconContainer: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabIconImage: {
    width: 20,
    height: 20,
    marginBottom: 3,
    tintColor: isDarkMode ? '#FFFFFF' : theme.background,
    resizeMode: 'contain',
  },
  notificationIconImage: {
    width: 28,
    height: 28,
    marginBottom: 3,
    tintColor: isDarkMode ? '#FFFFFF' : theme.background,
    resizeMode: 'contain',
  },
  activeTabIconImage: {
    transform: [{ scale: 1.1 }],
  },
  notificationBadge: {
    position: 'absolute',
    top: -8,
    right: -8,
    backgroundColor: '#FF4444',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  notificationBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  sosFab: {
    position: 'absolute',
    top: -65,
    left: '50%',
    marginLeft: -40,
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#2d3480',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  sosFabActive: {
    backgroundColor: '#4A90E2',
  },
  sosFabIcon: {
    width: 64,
    height: 64,
    resizeMode: 'contain',
  },
  modalContainer: {
    flex: 1,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
  },
  modalCloseButton: {
    padding: 8,
  },
  modalCloseText: {
    fontSize: fonts.body,
    fontWeight: '600',
  },
  modalTitle: {
    fontSize: fonts.subtitle,
    fontWeight: '600',
    color: theme.text,
  },
  modalHeaderSpacer: {
    width: 60,
  },
  // Font Size Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: isDarkMode ? 'rgba(0, 0, 0, 0.8)' : 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fontSizeModal: {
    backgroundColor: theme.background,
    borderRadius: 16,
    margin: 20,
    maxWidth: '90%',
    minWidth: '80%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  closeButton: {
    padding: 8,
  },
  closeButtonText: {
    fontSize: fonts.subtitle,
    color: theme.secondaryText,
    fontWeight: '600',
  },
  fontSizeOptions: {
    padding: 20,
  },
  fontSizeOption: {
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.menuBackground,
    marginBottom: 12,
  },
  fontSizeOptionSelected: {
    backgroundColor: isDarkMode ? 'rgba(30, 58, 138, 0.3)' : 'rgba(30, 58, 138, 0.1)',
    borderColor: theme.primary,
  },
  fontSizeOptionText: {
    fontSize: fonts.subtitle,
    color: theme.text,
    fontWeight: '600',
    marginBottom: 4,
  },
  fontSizeOptionTextSelected: {
    color: theme.primary,
  },
  fontSizeDescription: {
    fontSize: fonts.caption,
    color: theme.secondaryText,
  },
  fontSizeDescriptionSelected: {
    color: theme.primary,
  },
  // Language Modal Styles
  languageModal: {
    backgroundColor: theme.background,
    borderRadius: 16,
    margin: 20,
    maxWidth: '90%',
    minWidth: '80%',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  languageOptions: {
    padding: 20,
  },
  languageOption: {
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.menuBackground,
    marginBottom: 12,
  },
  languageOptionSelected: {
    backgroundColor: isDarkMode ? 'rgba(30, 58, 138, 0.3)' : 'rgba(30, 58, 138, 0.1)',
    borderColor: theme.primary,
  },
  languageOptionText: {
    fontSize: fonts.subtitle,
    color: theme.text,
    fontWeight: '600',
    marginBottom: 4,
  },
  languageOptionTextSelected: {
    color: theme.primary,
  },
  languageOptionDesc: {
    fontSize: fonts.caption,
    color: theme.secondaryText,
    lineHeight: 18,
  },
  languageOptionDescSelected: {
    color: theme.primary,
    opacity: 0.8,
  },
});

